=== Kari5/conference-portal/trunk/DataAccess-ejb/ejbModule/hu/bme/dtt/conferenceportal/db/init/init_users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- definition of simple elements -->
	<xs:element name="username" type="xs:string" />
	<xs:element name="password" type="xs:string" />
	<xs:element name="firstname" type="xs:string" />
	<xs:element name="lastname" type="xs:string" />
	<xs:element name="email" type="xs:string" />
	<xs:element name="tel" type="xs:string" />

	<xs:element name="rolename" type="xs:string" />

	<!-- definition of complex elements -->
	<xs:element name="role">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="rolename"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="user">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="username" />
				<xs:element ref="password" />
				<xs:element ref="firstname" minOccurs="0" />
				<xs:element ref="lastname" minOccurs="0" />
				<xs:element ref="email" minOccurs="0" />
				<xs:element ref="tel" minOccurs="0" />
				<xs:element ref="role" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="userlist">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="user" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== Kari5/conference-portal/DataAccess-ejb/ejbModule/hu/bme/dtt/conferenceportal/db/init/init_users.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Here you can specify the users to be loaded after deployment. If a role 
	assigned to one of these users doesn't exist, it will be created -->
<userlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="init_users.xsd">
	<user>
		<username>Superadmin</username>
		<password>admin</password>
		<firstname>Super</firstname>
		<lastname>Administrator</lastname>
		<role>
			<rolename>admin</rolename>
		</role>
	</user>
	<user>
		<username>TestUser</username>
		<password>test</password>
		<firstname>Test</firstname>
		<lastname>User</lastname>
		<email>test@user.test</email>
		<tel>1234567890</tel>
		<role>
			<rolename>user</rolename>
		</role>
	</user>
</userlist>
