=== Kari5/conference-portal/trunk/DataAccess-ejb/ejbModule/hu/bme/dtt/conferenceportal/db/init/init_permissions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- definition of simple elements -->
	<xs:element name="target" type="xs:string" />
	<xs:element name="action" type="xs:string" />
	<xs:element name="discriminator" type="xs:string" />
	<xs:element name="recipient" type="xs:string" />

	<!-- definition of complex elements -->

	<xs:element name="permission">
        <xs:complexType>
			<xs:sequence>
				<xs:element ref="target" />
				<xs:element ref="action" />
				<xs:element ref="discriminator" />
				<xs:element ref="recipient" />
			</xs:sequence>
		</xs:complexType>
    </xs:element>

	<xs:element name="permissionlist">
        <xs:complexType>
			<xs:sequence>
				<xs:element ref="permission" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
    </xs:element>

</xs:schema>

=== Kari5/conference-portal/DataAccess-ejb/ejbModule/hu/bme/dtt/conferenceportal/db/init/init_permissions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Here you can specify the permissions to be loaded after deployment. -->
<permissionlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="init_permissions.xsd">
	<!-- admin permissions -->
	<!-- seam.user -->
	<permission>
		<target>seam.user</target>
		<action>read</action>
		<discriminator>role</discriminator>
		<recipient>admin</recipient>
	</permission>
	<permission>
		<target>seam.user</target>
		<action>create</action>
		<discriminator>role</discriminator>
		<recipient>admin</recipient>
	</permission>
	<permission>
		<target>seam.user</target>
		<action>update</action>
		<discriminator>role</discriminator>
		<recipient>admin</recipient>
	</permission>
	<permission>
		<target>seam.user</target>
		<action>delete</action>
		<discriminator>role</discriminator>
		<recipient>admin</recipient>
	</permission>
	<!-- seam.role -->
	<permission>
		<target>seam.role</target>
		<action>read</action>
		<discriminator>role</discriminator>
		<recipient>admin</recipient>
	</permission>
	<permission>
		<target>seam.role</target>
		<action>create</action>
		<discriminator>role</discriminator>
		<recipient>admin</recipient>
	</permission>
	<permission>
		<target>seam.role</target>
		<action>update</action>
		<discriminator>role</discriminator>
		<recipient>admin</recipient>
	</permission>
	<permission>
		<target>seam.role</target>
		<action>delete</action>
		<discriminator>role</discriminator>
		<recipient>admin</recipient>
	</permission>
	
	<!-- user role permissions -->
	<!-- seam.user -->
	<permission>
		<target>seam.user</target>
		<action>update</action>
		<discriminator>role</discriminator>
		<recipient>user</recipient>
	</permission>
</permissionlist>
